version: '3.8'

services:
  app:
    build: .
    image: $APP_NAME
    container_name: next-container 
    volumes: 
      - $APP_VOLUMES_SRC:/app/
    ports: 
      - $PORT:3000
    command: npm run dev
